Docs/19 define the assignedtask with its description and constraints
Tascurator/tascurator-documents pull request #39
Opened 2024-03-07 23:32 UTC by yuki-92c

## Overview

- I added the descriptions and constraints of `AssignedTask`

## Changes

> ## AssignedTask - 割当タスク
> 
> ### taskId
> 
> - TaskId is the UUID
> 
> ### title
> 
> - The owner can set a title as they prefer. This title can be modified at any time.
> 
> Constraints:
> 
> - It must be between 1 and 20 characters in length.
> 
> ### description
> 
> - The owner can provide details for the task. This description can be modified at any time.
> 
> Constraints:
> 
> - The description must be between 10 and 120 characters.
> 
> ### completed
> 
> - Whether the task is completed or not.

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)

## Reviewer Checklist

- Code readability and simplicity
- Follows best practices and coding standards
- Understandable and maintainable code

2024-03-07 23:37 UTC, akiomatic commented
Could you revise the PR title as it does not follow our standard?
@yuki-92c

2024-03-07 23:42 UTC, akiomatic requested changes
Thank you for making changes, but could you revise the PR title too as it does not follow our standard?

2024-03-10 17:12 UTC, yuki-92c commented
> Thank you for making changes, but could you revise the PR title too as it does not follow our standard?

thanks for the comment and edited the title.

2024-03-10 19:29 UTC, KaiKoide requested changes

2024-03-10 19:29 UTC, KaiKoide commented on docs/docs/modeling.md
> +- It must be between 1 and 20 characters in length.
I think you don't follow the notation rules in terms of the bullet point. Could you modify that?
https://scrapbox.io/tascurator/%F0%9F%8F%B7%EF%B8%8F_GitHub%E3%81%AE%E9%81%8B%E7%94%A8%E3%83%AB%E3%83%BC%E3%83%AB

2024-03-10 19:29 UTC, KaiKoide commented on docs/docs/modeling.md
> +- The description must be between 10 and 120 characters.
same as above.

2024-03-10 22:40 UTC, Akikaze1119 approved these changes
Thank you! LGTM👍

2024-03-11 06:28 UTC, KaiKoide approved these changes
Thank you for the modifications! LGTM 👍

2024-03-11 19:52 UTC, HrRn approved these changes
Thank you!

2024-03-11 21:03 UTC, akiomatic approved these changes
Thank you for fixing the title:)

2024-06-14 18:33 UTC, merged